# Generated by Django 4.2.3 on 2023-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='tag', through='articles.Scope', to='articles.tag'),
        ),
    ]
