# Generated by Django 4.2.3 on 2023-08-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_scopes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Scopes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
    ]
